spring.application.name=demo

server.error.include-message=always
server.error.include-binding-errors=always
spring.jackson.mapper.accept-case-insensitive-enums=true
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.web.socket.messaging=DEBUG
logging.level.org.springframework.messaging.simp=DEBUG
logging.level.org.springframework.messaging.support=DEBUG
logging.level.org.springframework.web.socket.handler=DEBUG
logging.level.org.springframework.messaging.simp.stomp=TRACE


server_url=http://localhost:8080
