spring.application.name=demo

server.error.include-message=always
server.error.include-binding-errors=always
spring.jackson.mapper.accept-case-insensitive-enums=true

server_url=http://localhost:8080
